[package]
edition = "2021"
name = "shader"
version = "0.1.0"

[lib]
crate-type = ["lib", "dylib"]

[dependencies]
spirv-std = {git = "https://github.com/EmbarkStudios/rust-gpu.git", features = ["glam"]}
